severity: ["# blocker级别：中断缺陷（客户端程序无响应，无法执行下一步操作）","# critical级别：临界缺陷（ 功能点缺失）","# normal级别：普通缺陷（数值计算错误）","# minor级别：次要缺陷（界面错误与UI需求不符）","# trivial级别：轻微缺陷（必输项无提示，或者提示不规范）"]
feature: "用于描述被测试产品需求"
story: "用于描述feature的用户场景，即测试需求"
title: "用于描述用例名称"
description: "这是用例描述"