language: python # this works for Linux but is an error on macOS or Windows
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.6.10 on FreeBSD"
      os: freebsd
      language: python
    - name: "Python 3.7.6 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.6 running on macOS 10.11.1
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
before_install: # all three OSes agree about 'pip3'
  - python -m pip install --upgrade pip
install:
  - pip install --user -r requirements.txt --use-feature=2020-resolver
# 'python' points to Python 2.7 on macOS but points to Python 3.8 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
script: python3 RunAll.py || python RunAll.py