# 开发环境配置

# 数据库校验- mysql
database:
  host: '***'
  port: 3306
  user: 'root'
  # 不用''会被解析成int类型数据
  password: '***'
  db_name:  '***'
  charset:  utf8mb4

# 数据库所在的服务器配置
ssh_server:
  port: 22
  username: root
  password: 'password'
  # 私有密钥文件路径
  private_key_file:
  # 私钥密码
  privat_passowrd:
  # 如果使用的docker容器部署mysql服务，需要传入mysql的容器id/name
  mysql_container: mysql8
  # 数据库备份文件导出的本地路径, 需要保证存在该文件夹
  sql_data_file: backup_sqls/

# Redis配置
redis:
  host: '***'
  port: 6379
  auth: '***'
  index: 11
  encoding: "utf-8"
  decode_responses: True  # 获取中文数据可以直接 decode python unicode
  target_max_memory: '***'
  max_connections: 1