# 测试环境配置

email:
  # 发件人邮箱
  user:  user
  # 发件人邮箱授权码
  password:  password
  # 邮箱host
  host:  smtp.163.com
  contents:  请使用已安装Live Server 插件的VsCode或者其它Ide，打开index.html查看报告
  # 收件人邮箱
  addressees:  ["收件人邮箱1", "收件人邮箱2"]
  title:  接口自动化测试报告(见附件)
  # 附件
  enclosures: report.zip

# 数据库校验- mysql
database:
  host: localhost
  port: 3306
  user: root
  # 不用''会被解析成int类型数据
  password: 'password'
  db_name:  apiautotest
  charset:  utf8mb4

  # 数据库所在的服务器配置
  ssh_server:
    port: 22
    username: root
    password: 'password'
    # 私有密钥文件路径
    private_key_file:
    # 私钥密码
    privat_passowrd:
    # 如果使用的docker容器部署mysql服务，需要传入mysql的容器id/name
    mysql_container: mysql8
    # 数据库备份文件导出的本地路径, 需要保证存在该文件夹
    sql_data_file: backup_sqls/