site_name: ProtocolTest
site_description: A next-generation ApiTest client for Python.
site_url: https://www.python-ProtocolTest.org/

theme:
    name: 'material'

repo_name: encode/ProtocolTest
repo_url: https://github.com/encode/ProtocolTest/
edit_uri: ""

nav:
    - 介绍: 'index.md'
    - 快速入门: 'quickstart.md'
    - 高级用法: 'advanced.md'
    - 测试报告: 'push_message.md'
    - 持续集成: 'continue_integration.md'
    - 故障排除: 'troubleshooting.md'
    - 代码规范: 'code_of_conduct.md'
    - 第三方包: 'third_party_packages.md'
    - 其他贡献: 'contributing.md'

markdown_extensions:
  - admonition
  - codehilite:
      css_class: highlight

extra:
  search:
    language: 'zh'

extra_css:
    - css/custom.css

extra_javascript:
  - 'js/chat.js'
  - 'js/sidecar-1.5.0.js'
