# 基准的请求头信息
json_headers:
  accept: application/json,text/plain,*/*
  accept-encoding: gzip
  accept-language: zh-CN,zh;q=0.9
  content-type: application/json;charset=UTF-8
  user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36(KHTML, like Gecko) Chrome/89.0.5889.198 Safari/537.36

from_headers:
  accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
  accept-encoding: gzip
  accept-language: zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6
  content-type: application/x-www-form-urlencoded
  user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36(KHTML, like Gecko) Chrome/89.0.5889.198 Safari/537.36

get_headers:
  accept: text/css,*/*;q=0.1
  accept-encoding: gzip
  accept-language: zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6
  user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36(KHTML, like Gecko) Chrome/89.0.5889.198 Safari/537.36