Int: ${randInt}
Float: ${randFloat(10,5,2)}
Time: ${randTime(10timestamp)}
ComputeTime: ${randComputeTime()}
Letters: ${randLetters()}
Sample: ${randSample()}
Number: ${randNumber()}
Name: ${randName()}
Address: ${randAddress()}
Country: ${randCountry()}
CountryCode: ${randCountryCode()}
CityName: ${randCityName()}
City: ${randCity()}
Province: ${randProvince()}
Email: ${randEmail()}
Ipv4: ${randIpv4()}
Lipate: ${randLipate()}
Color: ${randColor()}
SafeHexColor: ${randSafeHexColor()}
ColorName: ${randColorName()}
CompanyName: ${randCompanyName()}
Job: ${randJob()}
Pwd: ${randPwd()}
Uuid4: ${randUuid4()}
Sha1: ${randSha1()}
Md5: ${randMd5()}
Female: ${randFemale()}
Male: ${randMale()}
UserInfo: ${randUserInfo()}
UserInfoPro: ${randUserInfoPro()}
UserAgent: ${randUserAgent()}
randPwd: ${randPwd()}